sudo: required

env:
  global:
    - ENVIRONMENT="travis"

services:
  - docker

language: php
php:
  - 5.6

before_install:
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  - composer install --dev
  - $TRAVIS_BUILD_DIR/vendor/kbrownell/drupal-caravan/setup-caravan.sh
