project:
  # Everyone: This will determine the the directory name of the new repository.
  # Dev Desktop users: this should match your local site name.
  # Used for enforcing correct git commit msg syntax.
  profile:
    # You can generate a custom profile by running '../vendor/bin/drupal generate:profile' from the docroot.
    name: 'standard'
  # This will be used as the local uri for all developers.
  local:
    uri: http://localhost
