---
#  vars_files:
#    - caravan.yml

- include: /var/www/earth/vendor/geerlingguy/drupal-vm/provisioning/playbook.yml

#    - name: setup BLT
#      when: ENV=acquia
#      include: tasks/setup-acquia.yml
#
#    - name: install site with BLT
#      when: ENV=acquia
#      include: tasks/install-acquia-site.yml
#
#    - name: setup Behat
#      include: tasks/setup-behat.yml
#
#    - name: run Behat
#      include: tasks/run-behat.yml
