---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml
    - config/caravan.yml

  tasks:
    - name: run drupalvm playbook
      include: tasks/run-drupalvm.yml

    - name: setup BLT
      when: ENV=acquia
      include: tasks/setup-acquia.yml

    - name: install site with BLT
      when: ENV=acquia
      include: tasks/install-acquia-site.yml

    - name: setup Behat
      include: tasks/setup-behat.yml

    - name: run Behat
      include: tasks/run-behat.yml
